export const THROW_POST_REQUEST = "QUESTION_CREATE_POST_REQUEST" as const;
export const CHANGE_QUESTION_CONTENT = "CHANGE_QUESTION_CONTENT" as const;
export const CHANGE_QUESTIONER_NAME = "CHANGE_QUESTIONER_NAME" as const;
export const CHANGE_QUESTION_TITLE = "CHANGE_QUESTION_TITLE" as const;
export const CREATE_QUESTION_SET_STACK_ID = "CREATE_QUESTION_SET_STACK_ID" as const;
export const SUCCESS = "CREATE_QUESTION_SUCCESS" as const;
export const FAILED = "CREATE_QUESTION_FAILED" as const;